/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Clinique { 
    active?: boolean;
    adress?: string;
    banqueName?: string;
    banqueNumber?: string;
    codeBureauxRegional?: string;
    codeCentre?: string;
    creationDate?: Date;
    employNumber?: string;
    id?: number;
    nom?: string;
    registreDeCmmerce?: string;
    tel?: string;
    tva?: string;
    updateDate?: Date;
}
