/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clinique } from './clinique';


export interface PriseEnCharge { 
    clinique?: Clinique;
    createUser?: string;
    creationDate?: Date;
    endDate?: string;
    id?: number;
    number?: string;
    startDate?: string;
    updateDate?: Date;
    updateUser?: string;
}
