/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Patient } from './patient';
import { SeanceType } from './seanceType';


export interface Seance { 
    createUser?: string;
    creationDate?: Date;
    date?: string;
    id?: number;
    patient?: Patient;
    seanceType?: SeanceType;
    updateDate?: Date;
    updateUser?: string;
}
