/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SeanceType { 
    EXONERE?: string;
    MSP?: string;
    MTHTAXE?: string;
    MTTVA?: string;
    createUser?: string;
    creationDate?: Date;
    exonere?: string;
    id?: number;
    msp?: string;
    mthtaxe?: string;
    mttva?: string;
    typeName?: string;
    updateDate?: Date;
    updateUser?: string;
}
