/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clinique } from './clinique';
import { Role } from './role';


export interface User { 
    active?: boolean;
    birthDate?: Date;
    clinique?: Clinique;
    creationDate?: Date;
    firstName?: string;
    id?: number;
    lastName?: string;
    login?: string;
    password?: string;
    roles?: Array<Role>;
    updateDate?: Date;
}
