version: '3.6'
services:
  angular:
    build: .
    command: ng serve --host 0.0.0.0 --poll=500
    ports:
      - 4200:4200
      - 49153:49153
    expose:
      - 4200
      - 49153
    volumes:
      - ./angular-project:/usr/app/angular-project
