export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './excelController.service';
import { ExcelControllerService } from './excelController.service';
export * from './halExplorer.service';
import { HalExplorerService } from './halExplorer.service';
export * from './operationHandler.service';
import { OperationHandlerService } from './operationHandler.service';
export * from './patientController.service';
import { PatientControllerService } from './patientController.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './seanceController.service';
import { SeanceControllerService } from './seanceController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './webMvcLinksHandler.service';
import { WebMvcLinksHandlerService } from './webMvcLinksHandler.service';
export const APIS = [BasicErrorControllerService, ExcelControllerService, HalExplorerService, OperationHandlerService, PatientControllerService, ProfileControllerService, SeanceControllerService, UserControllerService, WebMvcLinksHandlerService];
